#!/bin/bash
jekyll --no-auto
echo "Hello"
if [ $? -eq 0 ]
then
	echo "-*- Site Generated -*-";
	echo "-*-  Publishing... -*-";
	rsync -avz \
	  --delete \
	  --exclude="lavergne.gotdns.org/" \
	  --exclude="cgi-bin/" \
	  --exclude=".htaccess" \
	  ./_site/ wedaman@wedaman.com:public_html/;
else
	echo "-*-    Failure     -*-";
fi